kind: pipeline
name: front-end

steps:
- name: build-deploy-docker-image
  image: plugins/docker
  settings:
    registry: "localhost:32000"
    repo: "weather-web-app"
    tags: 
      - 0.0.1
    dockerfile: "./Dockerfile.yml"

