kind: pipeline
name: frontend

steps:
- name: build-deploy-docker-image
  image: plugins/docker
  settings:
    registry: "localhost:32000"
    repo: "front-end"
    tags: 
      - 0.0.1
    dockerfile: "./Dockerfile.yml"

