kind: pipeline
type: docker
name: frontend

steps:
- name: build-docker-image
  image: docker
  commands:
    -  echo Bulding docker image ...
    -  docker build -t weather-web-app:latest .
- name: docker-login
  image: docker
  environment:
    PASSWORD:
      from_secret: ne_password
    USERNAME:
      from_secret: ne_username
  commands:
    -  echo login to docker as user ...
    -  docker login -u $USERNAME -p $PASSWORD
    -  docker push  weather-web-app

