kind: pipeline
type: exec
name: frontend

steps:
- name: build-docker-image
  commands:
    -  echo Building docker image ...
    -  docker build -t weather-web-app:latest .
- name: docker-login
  environment:
    PASSWORD:
      from_secret: ne_password
    USERNAME:
      from_secret: ne_username
  commands:
    -  echo login to docker as user ...
    -  docker login https://reg.creativelab.top/repository/local-docker-image-registry/ -u $USERNAME -p $PASSWORD
    -  docker push  weather-web-app

