kind: pipeline
name: frontend

steps:
- name: build-deploy-docker-image
  image: plugins/docker
  settings:
    registry:
      from_secret: image_registry
    repo:
      from_secret: image_repository
    username:
      from_secret: ne_username
    password:
      from_secret: ne_password
    tags: 0.0.1
    dockerfile: "./Dockerfile.yml"

