kind: pipeline
name: frontend

steps:
- name: build-docker-image
  image: plugins/docker
  settings:
    tags:
    - develop
    dockerfile: ./Dockerfile.yml
- steps:
  name: sam_build
  image: harnesscommunity/drone-nexus-publish
  environment:
    PASSWORD:
      from_secret: ne_password
    USERNAME:
      from_secret: ne_username
  settings:
    username: $USERNAME
    password: $PASSWORD
    server_url: https://reg.creativelab.top
    filename: ./target/example.jar
    format: docker
    repository: local-docker-image-registry
    attributes: "-CgroupId=org.testing -CartifactId=example -Cversion=1.0 -Aextension=jar -Aclassifier=bin"
